# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_prior_rate <- function(sg, p, s_hat, g_hat, p_hat, R) {
    .Call(`_catalyticCDM_compute_prior_rate`, sg, p, s_hat, g_hat, p_hat, R)
}

compute_z_post_unnorm <- function(Y, R, p, sg) {
    .Call(`_catalyticCDM_compute_z_post_unnorm`, Y, R, p, sg)
}

row_sums <- function(X) {
    .Call(`_catalyticCDM_row_sums`, X)
}

sample_one_multinomial <- function(p) {
    .Call(`_catalyticCDM_sample_one_multinomial`, p)
}

sample_all_multinomial <- function(P) {
    .Call(`_catalyticCDM_sample_all_multinomial`, P)
}

compute_dina_probs <- function(eta, slip, guess) {
    .Call(`_catalyticCDM_compute_dina_probs`, eta, slip, guess)
}

sample_dina_data <- function(probs) {
    .Call(`_catalyticCDM_sample_dina_data`, probs)
}

compute_dina_probs_marginal <- function(Y, R, slip, guess, p) {
    .Call(`_catalyticCDM_compute_dina_probs_marginal`, Y, R, slip, guess, p)
}

compute_tau_lp <- function(tau, p, p_hat, slip, s_hat, guess, g_hat, pj_hat, tau_a, tau_b) {
    .Call(`_catalyticCDM_compute_tau_lp`, tau, p, p_hat, slip, s_hat, guess, g_hat, pj_hat, tau_a, tau_b)
}

